import Head from "next/head";
import Link from "next/link";
import { meta } from "./foo";

export default function Home() {
  const metaString =
    meta === undefined ? "undefined" : JSON.stringify(meta, null, 2);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>
        See the{" "}
        <Link href="/foo">
          <a>foo page</a>
        </Link>
        <pre>foo meta: {metaString}</pre>
      </p>
    </div>
  );
}
